
<?php
require 'GetTasks.class.php';
 
$tasks = getTasks();

?>

<table class="col-start-2 col-span-10">
<?php foreach ($tasks as $task): ?>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    <?php echo $task['taskName'] ?>
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <?php endforeach;; ?>
</table>