<table class="col-start-2 col-span-10">
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
  <tr class="grid grid-cols-12">
    <td class="border col-span-10 p-5">
    Task 1
    </td>
    <td class="border col-span-2 grid p-5 grid-cols-3 gap-5">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
    </td>
  </tr>
</table>


<!--
    <tr class="bg-gray-100 col-span-12">
        <td class="border px-4 py-2">Task 2</td>
        <td class="border px-4 py-2 grid-flow-row col-span-2">
        <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
      </td>
    </tr>
    <tr class="col-span-12">
      <td class="border px-4 py-2">Task 3</td>
      <td class="border px-4 py-2 grid-flow-row col-span-2">
      <span><img src="./images/view.png" class="w-10"></span>
        <span><img src="./images/edit.png" class="w-10"></span>
        <span><img src="./images/delete.png" class="w-10"></span>
      </td>
    </tr>

</table>

-->

<!--
    <div class="border grid col-start-2 col-span-4 grid-cols-5 gap-4 my-auto">
    <div class="col-span-4">Task number 1</div>
    <div class="bg-blue-400">icons to do different actions</div>
</div>




<div class="grid grid-rows-4 gap-4">
    <div class="bg-red-400 row-span-2">a</div>
    <div class="bg-blue-400">b</div>
    <div class="bg-yellow-400">c</div>
    <div class="bg-green-400">d</div>
</div>
-->