<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script src="https://cdn.tailwindcss.com"></script>
	</head>
	<body>
		<div class="container grid grid-cols-12 mx-auto text-center mb-10">

			<div class="text-4xl col-span-12 my-20 font-black underline decoration-8 decoration-blue-500">
				<h1 >To-do</h1>
			</div>
			<?php echo $this->content(); ?>
			
		</div>
	</body>
</html>